/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class HogwartsActor extends Actor {

  /**
   * @override
   * Store the preset skills at creation. The sheet addresses skills by array
   * index, so a character born with an empty stored list would have its first
   * skill edit written into the wrong slot, padding the array with blank rows.
   */
  async _preCreate(data, options, user) {
    const allowed = await super._preCreate(data, options, user);
    if (allowed === false) return false;
    if (this.type === 'character' && !this._source.system?.skills?.length) {
      const model = CONFIG.Actor.dataModels.character;
      this.updateSource({ 'system.skills': model.presetSkills() });
    }
    return allowed;
  }

  /** @override */
  prepareBaseData() {
    // IMPORTANT (Foundry v14): call super so that Actor#prepareBaseData runs
    // `_clearData()`, which resets the private `_completedActiveEffectPhases`
    // set each preparation cycle. Skipping it makes Active Effect application
    // throw "phase has already completed" on every update after the first.
    super.prepareBaseData();
    // Data modifications in this step occur before processing embedded
    // documents or derived data.
  }

  /**
   * @override
   * Augment the actor source data with additional dynamic data that isn't
   * handled by the actor's DataModel. Data calculated in this step should be
   * available both inside and outside of character sheets (such as if an actor
   * is queried and has a roll executed directly from it).
   */
  prepareDerivedData() {
    super.prepareDerivedData();
  }

  /**
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null.
   */
  getRollData() {
    return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
  }
}
